/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.b14.qdb.jni;

public class batch_request {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected batch_request(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(batch_request obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        qdbJNI.delete_batch_request(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public batch_request() {
    this(qdbJNI.new_batch_request__SWIG_0(), true);
  }

  public batch_request(qdb_operation_type_t t, String a, SWIGTYPE_p_qdb__api_buffer_ptr cont, SWIGTYPE_p_qdb__api_buffer_ptr comp, long exp) {
    this(qdbJNI.new_batch_request__SWIG_1(t.swigValue(), a, SWIGTYPE_p_qdb__api_buffer_ptr.getCPtr(cont), SWIGTYPE_p_qdb__api_buffer_ptr.getCPtr(comp), exp), true);
  }

  public batch_request(qdb_operation_type_t t, String a, SWIGTYPE_p_qdb__api_buffer_ptr cont, SWIGTYPE_p_qdb__api_buffer_ptr comp) {
    this(qdbJNI.new_batch_request__SWIG_2(t.swigValue(), a, SWIGTYPE_p_qdb__api_buffer_ptr.getCPtr(cont), SWIGTYPE_p_qdb__api_buffer_ptr.getCPtr(comp)), true);
  }

  public batch_request(qdb_operation_type_t t, String a, SWIGTYPE_p_qdb__api_buffer_ptr cont) {
    this(qdbJNI.new_batch_request__SWIG_3(t.swigValue(), a, SWIGTYPE_p_qdb__api_buffer_ptr.getCPtr(cont)), true);
  }

  public batch_request(qdb_operation_type_t t, String a) {
    this(qdbJNI.new_batch_request__SWIG_4(t.swigValue(), a), true);
  }

  public void setType(qdb_operation_type_t value) {
    qdbJNI.batch_request_type_set(swigCPtr, this, value.swigValue());
  }

  public qdb_operation_type_t getType() {
    return qdb_operation_type_t.swigToEnum(qdbJNI.batch_request_type_get(swigCPtr, this));
  }

  public void setAlias(String value) {
    qdbJNI.batch_request_alias_set(swigCPtr, this, value);
  }

  public String getAlias() {
    return qdbJNI.batch_request_alias_get(swigCPtr, this);
  }

  public void setContent(SWIGTYPE_p_qdb__api_buffer_ptr value) {
    qdbJNI.batch_request_content_set(swigCPtr, this, SWIGTYPE_p_qdb__api_buffer_ptr.getCPtr(value));
  }

  public SWIGTYPE_p_qdb__api_buffer_ptr getContent() {
    return new SWIGTYPE_p_qdb__api_buffer_ptr(qdbJNI.batch_request_content_get(swigCPtr, this), true);
  }

  public void setComparand(SWIGTYPE_p_qdb__api_buffer_ptr value) {
    qdbJNI.batch_request_comparand_set(swigCPtr, this, SWIGTYPE_p_qdb__api_buffer_ptr.getCPtr(value));
  }

  public SWIGTYPE_p_qdb__api_buffer_ptr getComparand() {
    return new SWIGTYPE_p_qdb__api_buffer_ptr(qdbJNI.batch_request_comparand_get(swigCPtr, this), true);
  }

  public void setExpiry_time(long value) {
    qdbJNI.batch_request_expiry_time_set(swigCPtr, this, value);
  }

  public long getExpiry_time() {
    return qdbJNI.batch_request_expiry_time_get(swigCPtr, this);
  }

}
