/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.b14.qdb.jni;

public class error_carrier {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected error_carrier(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(error_carrier obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        qdbJNI.delete_error_carrier(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public error_carrier() {
    this(qdbJNI.new_error_carrier(), true);
  }

  public void setError(qdb_error_t value) {
    qdbJNI.error_carrier_error_set(swigCPtr, this, value.swigValue());
  }

  public qdb_error_t getError() {
    return qdb_error_t.swigToEnum(qdbJNI.error_carrier_error_get(swigCPtr, this));
  }

}
