/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.b14.qdb.jni;

public final class qdb_option_t {
  public final static qdb_option_t option_operation_timeout = new qdb_option_t("option_operation_timeout", qdbJNI.option_operation_timeout_get());
  public final static qdb_option_t option_log_callback = new qdb_option_t("option_log_callback", qdbJNI.option_log_callback_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static qdb_option_t swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + qdb_option_t.class + " with value " + swigValue);
  }

  private qdb_option_t(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private qdb_option_t(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private qdb_option_t(String swigName, qdb_option_t swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static qdb_option_t[] swigValues = { option_operation_timeout, option_log_callback };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

