/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.b14.qdb.jni;

public class qdb_operation_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected qdb_operation_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(qdb_operation_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        qdbJNI.delete_qdb_operation_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(qdb_operation_type_t value) {
    qdbJNI.qdb_operation_t_type_set(swigCPtr, this, value.swigValue());
  }

  public qdb_operation_type_t getType() {
    return qdb_operation_type_t.swigToEnum(qdbJNI.qdb_operation_t_type_get(swigCPtr, this));
  }

  public void setAlias(String value) {
    qdbJNI.qdb_operation_t_alias_set(swigCPtr, this, value);
  }

  public String getAlias() {
    return qdbJNI.qdb_operation_t_alias_get(swigCPtr, this);
  }

  public void setContent(java.nio.ByteBuffer value) {
    qdbJNI.qdb_operation_t_content_set(swigCPtr, this, value);
  }

  public java.nio.ByteBuffer getContent() { return qdbJNI.qdb_operation_t_content_get(swigCPtr, this); }

  public void setContent_size(long value) {
    qdbJNI.qdb_operation_t_content_size_set(swigCPtr, this, value);
  }

  public long getContent_size() {
    return qdbJNI.qdb_operation_t_content_size_get(swigCPtr, this);
  }

  public void setComparand(java.nio.ByteBuffer value) {
    qdbJNI.qdb_operation_t_comparand_set(swigCPtr, this, value);
  }

  public java.nio.ByteBuffer getComparand() { return qdbJNI.qdb_operation_t_comparand_get(swigCPtr, this); }

  public void setComparand_size(long value) {
    qdbJNI.qdb_operation_t_comparand_size_set(swigCPtr, this, value);
  }

  public long getComparand_size() {
    return qdbJNI.qdb_operation_t_comparand_size_get(swigCPtr, this);
  }

  public void setExpiry_time(long value) {
    qdbJNI.qdb_operation_t_expiry_time_set(swigCPtr, this, value);
  }

  public long getExpiry_time() {
    return qdbJNI.qdb_operation_t_expiry_time_get(swigCPtr, this);
  }

  public qdb_error_t getError() {
    return qdb_error_t.swigToEnum(qdbJNI.qdb_operation_t_error_get(swigCPtr, this));
  }

  public java.nio.ByteBuffer getResult() { return qdbJNI.qdb_operation_t_result_get(swigCPtr, this); }

  public long getResult_size() {
    return qdbJNI.qdb_operation_t_result_size_get(swigCPtr, this);
  }

  public qdb_operation_t() {
    this(qdbJNI.new_qdb_operation_t(), true);
  }

}
