/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.b14.qdb.jni;

public class qdb_const_iterator_t {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected qdb_const_iterator_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(qdb_const_iterator_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        qdbJNI.delete_qdb_const_iterator_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIGTYPE_p_qdb_session getHandle() {
    long cPtr = qdbJNI.qdb_const_iterator_t_handle_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_qdb_session(cPtr, false);
  }

  public SWIGTYPE_p_void getToken() {
    long cPtr = qdbJNI.qdb_const_iterator_t_token_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SWIGTYPE_p_void getNode() {
    long cPtr = qdbJNI.qdb_const_iterator_t_node_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SWIGTYPE_p_void getRef() {
    long cPtr = qdbJNI.qdb_const_iterator_t_ref_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public String getAlias() {
    return qdbJNI.qdb_const_iterator_t_alias_get(swigCPtr, this);
  }

  public java.nio.ByteBuffer getContent() { return qdbJNI.qdb_const_iterator_t_content_get(swigCPtr, this); }

  public long getContent_size() {
    return qdbJNI.qdb_const_iterator_t_content_size_get(swigCPtr, this);
  }

  public qdb_const_iterator_t() {
    this(qdbJNI.new_qdb_const_iterator_t(), true);
  }

}
