/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.b14.qdb.jni;

public class remoteNodeArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected remoteNodeArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(remoteNodeArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        qdbJNI.delete_remoteNodeArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public remoteNodeArray() {
    this(qdbJNI.new_remoteNodeArray__SWIG_0(), true);
  }

  public remoteNodeArray(long n) {
    this(qdbJNI.new_remoteNodeArray__SWIG_1(n), true);
  }

  public long size() {
    return qdbJNI.remoteNodeArray_size(swigCPtr, this);
  }

  public long capacity() {
    return qdbJNI.remoteNodeArray_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    qdbJNI.remoteNodeArray_reserve(swigCPtr, this, n);
  }

  public boolean empty() {
    return qdbJNI.remoteNodeArray_empty(swigCPtr, this);
  }

  public void clear() {
    qdbJNI.remoteNodeArray_clear(swigCPtr, this);
  }

  public void push_back(qdb_remote_node_t x) {
    qdbJNI.remoteNodeArray_push_back(swigCPtr, this, qdb_remote_node_t.getCPtr(x), x);
  }

  public qdb_remote_node_t get(int i) {
    return new qdb_remote_node_t(qdbJNI.remoteNodeArray_get(swigCPtr, this, i), false);
  }

  public void set(int i, qdb_remote_node_t val) {
    qdbJNI.remoteNodeArray_set(swigCPtr, this, i, qdb_remote_node_t.getCPtr(val), val);
  }

}
