/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.b14.qdb.jni;

public class StringVec {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected StringVec(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StringVec obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        qdbJNI.delete_StringVec(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public StringVec() {
    this(qdbJNI.new_StringVec__SWIG_0(), true);
  }

  public StringVec(long n) {
    this(qdbJNI.new_StringVec__SWIG_1(n), true);
  }

  public long size() {
    return qdbJNI.StringVec_size(swigCPtr, this);
  }

  public long capacity() {
    return qdbJNI.StringVec_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    qdbJNI.StringVec_reserve(swigCPtr, this, n);
  }

  public boolean empty() {
    return qdbJNI.StringVec_empty(swigCPtr, this);
  }

  public void clear() {
    qdbJNI.StringVec_clear(swigCPtr, this);
  }

  public void push_back(String x) {
    qdbJNI.StringVec_push_back(swigCPtr, this, x);
  }

  public String get(int i) {
    return qdbJNI.StringVec_get(swigCPtr, this, i);
  }

  public void set(int i, String val) {
    qdbJNI.StringVec_set(swigCPtr, this, i, val);
  }

}
