/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.5
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.b14.qdb.jni;

public class SWIGTYPE_p_qdb__api_buffer_ptr {
  private long swigCPtr;

  protected SWIGTYPE_p_qdb__api_buffer_ptr(long cPtr, boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_qdb__api_buffer_ptr() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_qdb__api_buffer_ptr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

